import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home/Home.module.css'
import Link from 'next/link'
import Header from '../components/home/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Never-Over</title>
        <meta name="Never-Over" content="Generated by create next app" />
        <link rel="icon" href="/never.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600&display=swap" rel="stylesheet" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        {/* ---------------- */}
        <div className={styles.welcome}>
          {/* ---------------- */}
          <section className={styles.fondoContain}>
            <div className={styles.fondo}>
              <h1><Link href="/home/about">Never-Over</Link></h1>
            </div>
          </section>
          {/* ---------------- */}
          <section className={styles.proyects}>
            <h1>Proyects</h1>
            <div className={styles.proyects_contain}>
              <div className={styles.proyect}>
                <Link href="/proyets/never-money" className={styles.proyect_money}>
                  <button>Never-Money</button>
                </Link>
              </div>
              <div className={styles.proyect}>
                <Link href="/proyets/never-money" className={styles.proyect_time}>
                  <button>Never-Time</button>
                </Link>
              </div>
              <div className={styles.proyect}>
                <Link href="/proyets/never-money" className={styles.proyect_more}>
                  <button>More-Proyects</button>
                </Link>
              </div>

            </div>
          </section>
        </div>
        {/* ---------------- */}
        <section className={styles.descripcion}>
          <Image src="/logoWhite.png" alt="Vercel Logo" width={220} height={220} />
          <h1>Nunca se finalizo algun...</h1>
          <ul>
            <li>Proyecto personal</li>
            <li>Pagina web</li>
            <li>Automatizacion de algun dispositivo</li>
          </ul>
          <div className={styles.proyectoSinAcabar}>
            {/* <Link href="/home/about" className={styles.linkMenu}>
              <Image src="/image/cohete.png" alt="Vercel Logo" width={180} height={180} />
            </Link> */}
          </div>
          <hr />

          <p>¿Tienes un proyecto en mente, necesitas una pagina web, quieres desarrollar una aplicacion o automatizar algun dispositivo?</p>

          <Link href="/home/contact" className={styles.linkMenu}>
            <button>Contact Me</button>
          </Link>

        </section>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
