import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home/Home.module.css'
import Link from 'next/link'
import Header from '../components/home/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Never-Over</title>
        <meta name="Never-Over" content="Generated by create next app" />
        <link rel="icon" href="/never.png" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        {/* ---------------- */}
        <section className={styles.welcome}>
          <div className={styles.fondo}>
            <h1><Link href="/home/about">Never-Over</Link></h1>

          </div>
        </section>

        {/* ---------------- */}
        <section className={styles.proyects}>
          <h1>Proyects</h1>
        </section>

        {/* ---------------- */}
        <section className={styles.descripcion}>
          <h1>Nunca se finalizo algun...</h1>
          <ul>
            <li>Proyecto personal</li>
            <li>Pagina web</li>
            <li>Automatizacion de algun dispositivo</li>
          </ul>
          <hr />
          {/* <Image src="/logoWhite.png" alt="Vercel Logo" width={220} height={220} /> */}
          <p>¿Tienes un proyecto en mente, necesitas una pagina web, quieres desarrollar una aplicacion o automatizar algun dispositivo?</p>
          <button>
            <Link href="/home/about" className={styles.linkMenu}>Contact Me</Link>
          </button>
        </section>


        {/* ---------------- */}
        {/* <div className={styles.proyects}>
          <Link href="/" className={styles.proyect}> 
            <div>
              <h1>Never-Money</h1>
            </div>
          </Link>
        
        </div> */}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
